### ISSUE TITLE
Visually clarify view-new-window vs download functionality

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs-shipyard/ipfs-share-files#105]
Per @autonome note in Jan 2021 hack week:

> Be able to view (mime detect) instead of download, with something in URL that indicates that for share links.

This isn't looking like it'll make the time crunch for the week, so capturing in an issue for later inclusion.
Community PRs are **more than welcome!** :)

**Comment by lidel** [comment]
I think.. "download" is already implemented on download page.
@jessicaschilling I made a quick overwiew of how things look like at https://dev.share.ipfs.io/ atm:

## Sharing page:

Here we only copy the "view" link, because that makes the most sense when sharing direct links to things that can be viewed in browser (images, PDFs):

> ![2021-02-04--12-50-27](https://user-images.githubusercontent.com/157609/106888971-9d737480-66e7-11eb-9ec9-6df9b481ce0c.png)

- both blue one and green one point at "view": https://dweb.link/ipfs/bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi?filename=guardian.jpg

## Download page:

Here we have "view" and "download" actions, so receiver can make a decision if they want to save file or view it:

> ![2021-02-04--12-53-07](https://user-images.githubusercontent.com/157609/106889171-f0e5c280-66e7-11eb-8ef2-628a335f4675.png)

- green (view):  https://dweb.link/ipfs/bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi?filename=guardian.jpg
- blue (download) will open: https://dweb.link/ipfs/bafybeigdyrzt5sfp7udm7hu76uh7y26nf3efuylqabf3oclgtqy55fbzdi?filename=guardian.jpg&download=true (`download=true` makes browser download instead rendering)


----

**Comment by autonome** [comment]
I'd love for "view" to be explicit in the design instead of implicit via
the filename being a link. Eg, an 👁 button next to the download arrow
button, or something like that.

**Comment by jessicaschilling** [comment]
Agree it's less than ideal. MUCH better than it was a week ago but will see if we can improve within the boundaries of the hack week - else will open a new issue to reduce confusion.
